#!/usr/bin/env python

import os
import sys
import subprocess
from fabricate import *

MAXCOMPILERDIR = '/network-raid/opt/maxcompiler-2015.1-rc1/' # os.environ['MAXCOMPILERDIR']
CLASSPATH = os.environ['CLASSPATH']

MAXCOMPILER = 'maxjc'
MAXDEBUG = 'source,lines,vars'
MAXSOURCE = '1.6'
MAXTARGET = '1.6'
MAXCLASSPATH = ['%s/lib/MaxCompiler.jar' % MAXCOMPILERDIR]

MAXDESTDIR = 'bin'
MAXSRCDIR = 'HTTP-Web-Server'

# build directory - .max file location
result=os.environ.get('MAXCOMPILER_BUILD_CONF')

JAVARTENV = '/network-raid/opt/jdk1.6.0_02/jre/bin/java'
JAVAMAXHEAPSIZE = 'mx12288m' #-Xmx<size> set maximum Java heap size
HTTPSERVERCLASSPATH = ['./bin']  + [CLASSPATH]
DFEMODEL='ISCA' 
MAXFILENAME='httpserver'
HTTPSERVERSTARTUPCLASS = 'httpServer.HttpServerManager'


message = "Valid argument format: make < dfe | sim >"
if __name__ == '__main__':
	if len(sys.argv) == 2:
		#PORT_VAR = int(sys.argv[1])
		ARG_VAR = sys.argv[1]
		if (ARG_VAR != 'dfe') and (ARG_VAR != 'sim'):
			sys.exit(message)
		if ARG_VAR == 'dfe':
			TARGET = 'DFE'
			os.environ["MAXCOMPILER_BUILD_CONF"] = "build.copy_results_to = /tmp/maxbuild/maxdc_builds/DFE/;"
		else:
			TARGET = 'DFE_SIM'
			os.environ["MAXCOMPILER_BUILD_CONF"] = "build.copy_results_to = /tmp/maxbuild/maxdc_builds/DFE_SIM/;"
	else:
		sys.exit(message)

def sim():    
    build()

def dfe():
    build()

def build():
    clean()
    compile_java()
    execute_java_maxJavaRun()


# compile java
# command
def compile_java():
    print "\n*** Compile Java *** \n"
    run(MAXCOMPILER, '-nowarn', '-g:%s' % MAXDEBUG, '-source', '%s' % MAXSOURCE, 
        '-target', '%s' % MAXTARGET, '-classpath', '%s' % ':'.join(MAXCLASSPATH), 
        '-d', '%s' % MAXDESTDIR, MAXSRCDIR)

def execute_java_maxJavaRun():
    print "\n*** Execute Java *** \n"
    Temp = ' '.join(['CLASSPATH=%s' % ':'.join(HTTPSERVERCLASSPATH), 'maxJavaRun', HTTPSERVERSTARTUPCLASS, 'DFEModel=%s' % DFEMODEL, 'maxFileName=%s' % MAXFILENAME, 'target=%s' % TARGET])
    subprocess.check_call(Temp, shell=True)

def clean():
    autoclean()

main()
