#!/usr/bin/env python

import os
import sys
import subprocess
from fabricate import *

NAME="httpServer"

from fabricate import *

sources = ['main','HttpRequest', 'init', 'crc16']

# Define compiler flags
flags = ['-g', '-I../%s' % 'include']

def build():
    clean()
    compile()
    link()

def compile():
    for source in sources:
        run('gcc', flags, '-c', source + '.c')

def link():
    objects = [s+'.o' for s in sources]
    run('gcc', '-lm', objects,'-o', NAME)

def execute_program():
    run('./%s' % NAME)

def clean():
    autoclean()

main()
