#!/usr/bin/env python

import os
import sys
import subprocess
from fabricate import *

NAME="httpServer"
output_dir='gen'
input_dir='docopt-c'
docopt_file='http-server.docopt'
output_gen_name='cGenDopt.c'


from fabricate import *

sources = ['main','HttpRequest', 'init', 'crc16']

# Define compiler flags
flags = ['-g', '-Iinclude', '-Igen']

def build():
    run_docopt_c()
    compile()
    link()

def run_docopt_c():
        run('python', input_dir + '/' + 'docopt_c.py', '-o', output_dir + '/' + output_gen_name, docopt_file)

def compile():
    for source in sources:
        run('gcc', flags, '-c', 'src/%s' % source + '.c')

def link():
    objects = [s+'.o' for s in sources]
    run('gcc', '-lm', objects,'-o', NAME)

def execute_program():
    run('./%s' % NAME)

main()
